theme = "blowfish"
languageCode = "es"
enableRobotsTXT = true
summaryLength = 30
buildDrafts = false
buildFuture = false
enableEmoji = true
baseURL = "https://brillaverde.github.io"
googleAnalytics = ""

[pagination]
pagerSize = 20

[taxonomies]
tag = "tags"
category = "Categorias"
author = "authors"
series = "series"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = [ "HTML", "RSS", "JSON" ]
