---
title: "BrillaVerde: Una comunidad energética pionera en Villaverde"
date: 2025-11-17
format: docx
---

_¡Algo nuevo brilla en Villaverde!_ Se trata de [BrillaVerde](https://brillaverde.org/), la primera comunidad energética de Villaverde, creada por vecinas y vecinos del barrio de Butarque que aspira a extenderse por todo del distrito. 

La iniciativa surgió a partir de un grupo de vecinas de este barrio preocupadas por el cambio climático y la necesidad urgente de adoptar fuentes de energía más limpias y sostenibles, y rápidamente contó con el apoyo de las asociaciones vecinales y otros colectivos como las AMPAs del barrio. Tras varios meses de reuniones para definir los objetivos y la estructura de la comunidad, y darla a conocer en el distrito, el pasado 28 de mayo se constituyó oficialmente la comunidad energética con más de 50 miembros fundadores.

Uno de los principales objetivos de la comunidad energética es aprovechar las cubiertas de los espacios públicos del barrio para generar energía renovable, principalmente a través de la instalación de paneles solares en edificios comunitarios (colegios, bibliotecas, centros centros deportivos, etc.) y para ello se ha instado al Ayuntamiento de Madrid a que ceda estos espacios a comunidades como la nuestra, por lo que esperamos poder disponer de alguna de estas cubiertas en breve. Nos gustaría marcar un hito en la transición hacia un modelo energético más sostenible y participativo, siendo la primera planta de energía renovable comunitaria con modelo cesión de uso de un edificio público en el Ayuntamiento de Madrid.

**¿Quiénes pueden formar parte de BrillaVerde?
**

Cualquier persona, pequeña empresa o entidad puede asociarse, pero actualmente se contemplan dos tipos de personas o entidades socias: _socias colaboradoras_, quienes quieren contribuir a los fines de la comunidad, aunque no están interesadas en consumir la energía generada por esta, y _socias energéticas_, quienes sí están interesadas en consumir la energía generada por la comunidad. En el último caso, de acuerdo a la normativa vigente, los domicilios de las socias energéticas deben estar ubicados a una distancia máxima de 2 km de la planta de generación, aunque se espera que en breve el gobierno amplíe esta distancia a 5 km, con lo que prácticamente cualquier persona o pequeña empresa del distrito podría ser socia energética.

Las socias energéticas podrán adquirir un título energético con una determinada potencia nominal y recibirán la energía generada proporcionalmente a la potencia nominal adquirida.

La comunidad ha empezado ya a realizar distintos talleres para que las socias energéticas puedan entender sus facturas eléctricas y hagan una estimación de su consumo para saber qué potencia nominal necesitan adquirir. También se están visitando los distintos comercios del barrio para informarles de la iniciativa y animarles a formar parte de este proyecto.

Así que, ya sabes, si vives o tienes un negocio en Villaverde, si te preocupa como a nosotras el cambio climático, si quieres reducir tu factura eléctrica apostando por un modelo energético más justo y sostenible, o simplemente si te preocupas por tu barrio y quieres crear comunidad con tus vecinas, no dudes en unirte a BrillaVerde y formar parte de esta revolución energética comunitaria. Juntas podemos hacer que Villaverde brille con energía renovable. ¡Te esperamos!

Puedes inscribirte en nuestra web [https://brillaverde.org](https://brillaverde.org/).
